'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { demoQuestions } from '@/lib/academy/demo-data';
import { hasDemoRegistration } from '@/lib/academy/demo-session';
import Registration from '@/app/(publicGroup)/_components/academy/registration';
import '../../home.css';
export default function FreeExam() {
 const [ready, setReady] = useState(false); const [registered, setRegistered] = useState(false); const [open, setOpen] = useState(false);
 const [answers, setAnswers] = useState<Record<string, number>>({}); const [submitted, setSubmitted] = useState(false);
 useEffect(() => { setRegistered(hasDemoRegistration()); setReady(true); }, []);
 // BACKEND: submit attempt to a server endpoint; never ship answer keys in real exams.
 const score = demoQuestions.filter(q => answers[q.id] === q.correctIndex).length;
 return <main lang="bn" className="academy-home min-h-screen px-5 pt-32 pb-20"><div className="mx-auto max-w-3xl"><p className="academy-eyebrow">FREE PRACTICE EXAM</p><h1 className="mt-3 text-3xl font-bold">ফ্রি মূল্যায়ন পরীক্ষা</h1><p className="mt-4 text-muted-foreground">৩টি প্রশ্ন · প্রতিটি সঠিক উত্তরে ১ নম্বর · নেগেটিভ মার্কিং নেই</p>{!ready ? <p className="mt-8" role="status">লোড হচ্ছে…</p> : !registered ? <div className="mt-8 rounded-2xl border p-6"><p className="mb-4">পরীক্ষা শুরু করতে ডেমো রেজিস্ট্রেশন সম্পন্ন করুন।</p><Button onClick={() => setOpen(true)} className="academy-primary rounded-full">রেজিস্ট্রেশন করুন</Button></div> : <form onSubmit={e => { e.preventDefault(); setSubmitted(true); }} className="mt-8 space-y-5">{demoQuestions.map((q, index) => <fieldset key={q.id} disabled={submitted} className="rounded-2xl border bg-card p-5 text-card-foreground"><legend className="px-2 font-semibold">{index+1}. {q.text}</legend><div className="grid gap-3 sm:grid-cols-2">{q.options.map((option, i) => <label key={option} className="flex cursor-pointer items-center gap-3 rounded-xl border p-3 has-checked:border-sky-500 has-checked:bg-sky-500/10"><input required type="radio" name={q.id} value={i} checked={answers[q.id] === i} onChange={() => setAnswers({ ...answers, [q.id]: i })} className="size-4 accent-sky-700" /><span>{option}</span></label>)}</div>{submitted && <p className="mt-4 text-sm leading-7">{answers[q.id] === q.correctIndex ? '✓ সঠিক। ' : '✕ ভুল। '}সঠিক উত্তর: {q.options[q.correctIndex]}। {q.explanation}</p>}</fieldset>)}{submitted ? <div role="status" className="rounded-2xl border bg-muted p-6"><h2 className="text-2xl font-bold">আপনার স্কোর: {score} / {demoQuestions.length}</h2><Button type="button" variant="outline" className="mt-4 rounded-full" onClick={() => { setAnswers({}); setSubmitted(false); }}>আবার চেষ্টা করুন</Button></div> : <Button className="academy-primary rounded-full" disabled={Object.keys(answers).length !== demoQuestions.length}>উত্তর জমা দিন</Button>}</form>}<p className="my-6 text-xs text-muted-foreground">ডেমো পরীক্ষা—ফলাফল সার্ভারে সংরক্ষিত হয় না।</p><Link href="/" className="academy-accent underline">হোমপেজে ফিরুন</Link><Registration open={open} onOpenChange={value => { setOpen(value); if (!value) setRegistered(hasDemoRegistration()); }} /></div></main>;
}
