import type { StudentData } from "./types";
export const studentDemo: StudentData = {
  profile: {
    name: "ডেমো শিক্ষার্থী",
    email: "student@example.com",
    goal: "বিসিএস প্রিলিমিনারি",
    id: "AR-DEMO-1024",
  },
  questions: [
    {
      id: "q1",
      subject: "বাংলা",
      text: "বাংলা ভাষার আদি নিদর্শন কোনটি?",
      options: ["চর্যাপদ", "শ্রীকৃষ্ণকীর্তন", "মঙ্গলকাব্য", "মেঘনাদবধ কাব্য"],
      answer: 0,
      explanation: "চর্যাপদ বাংলা ভাষা ও সাহিত্যের প্রাচীনতম নিদর্শন।",
    },
    {
      id: "q2",
      subject: "ইংরেজি",
      text: "Choose the correct spelling.",
      options: [
        "Accomodation",
        "Accommodation",
        "Acommodation",
        "Accommadation",
      ],
      answer: 1,
      explanation: "সঠিক বানান Accommodation — দুটি c এবং দুটি m রয়েছে।",
    },
    {
      id: "q3",
      subject: "গণিত",
      text: "একটি সংখ্যার ২৫% হলো ২০। সংখ্যাটি কত?",
      options: ["৪০", "৬০", "৮০", "১০০"],
      answer: 2,
      explanation: "সংখ্যাটি = ২০ × ১০০ ÷ ২৫ = ৮০।",
    },
    {
      id: "q4",
      subject: "সাধারণ জ্ঞান",
      text: "বাংলাদেশের জাতীয় স্মৃতিসৌধ কোথায় অবস্থিত?",
      options: ["রমনা", "সাভার", "টুঙ্গিপাড়া", "সোনারগাঁও"],
      answer: 1,
      explanation: "জাতীয় স্মৃতিসৌধ ঢাকার সাভারে অবস্থিত।",
    },
    {
      id: "q5",
      subject: "বিজ্ঞান",
      text: "পানির রাসায়নিক সংকেত কী?",
      options: ["CO₂", "O₂", "H₂O", "NaCl"],
      answer: 2,
      explanation:
        "পানির একটি অণুতে দুটি হাইড্রোজেন ও একটি অক্সিজেন পরমাণু থাকে।",
    },
  ],
  exams: [
    {
      id: "live-1",
      title: "বিসিএস প্রস্তুতি • মিশ্র বিষয়",
      subject: "সব বিষয়",
      kind: "live",
      date: "ডেমোতে এখনই অংশ নিন",
      questions: ["q1", "q2", "q3", "q4", "q5"],
    },
    {
      id: "free-1",
      title: "ফ্রি মডেল টেস্ট ০১",
      subject: "সব বিষয়",
      kind: "free",
      date: "যেকোনো সময় অনুশীলন",
      questions: ["q1", "q2", "q3", "q4", "q5"],
    },
    {
      id: "free-2",
      title: "ভাষা দক্ষতা যাচাই",
      subject: "বাংলা ও ইংরেজি",
      kind: "free",
      date: "যেকোনো সময় অনুশীলন",
      questions: ["q1", "q2"],
    },
    {
      id: "next-1",
      title: "প্রাইমারি প্রস্তুতি • সাপ্তাহিক পরীক্ষা",
      subject: "সব বিষয়",
      kind: "upcoming",
      date: "সময়সূচি শীঘ্রই প্রকাশিত হবে",
      questions: ["q1", "q2", "q3", "q4", "q5"],
    },
  ],
  courses: [
    {
      id: "bcs",
      title: "বিসিএস প্রিলিমিনারি প্রস্তুতি",
      category: "BCS PREPARATION",
      description: "বিষয়ভিত্তিক প্রস্তুতি, রিভিশন ও মডেল টেস্ট।",
      completed: 2,
      lessons: [
        "প্রস্তুতির পরিকল্পনা",
        "বাংলা ভাষা ও সাহিত্য",
        "ইংরেজি গ্রামার",
        "গণিতের ভিত্তি",
        "বাংলাদেশ বিষয়াবলি",
        "চূড়ান্ত রিভিশন",
      ],
      enrolled: true,
      color: "cyan",
    },
    {
      id: "english",
      title: "বেসিক টু অ্যাডভান্সড ইংরেজি",
      category: "ENGLISH FOUNDATION",
      description: "গ্রামার ও শব্দভান্ডারের শক্ত ভিত গড়ে তুলুন।",
      completed: 1,
      lessons: [
        "Parts of speech",
        "Tense",
        "Vocabulary",
        "Sentence correction",
      ],
      enrolled: true,
      color: "violet",
    },
    {
      id: "primary",
      title: "প্রাইমারি শিক্ষক নিয়োগ প্রস্তুতি",
      category: "PRIMARY PREPARATION",
      description: "বাংলা, গণিত ও সাধারণ জ্ঞানের সমন্বিত প্রস্তুতি।",
      completed: 0,
      lessons: ["পরিচিতি ও সিলেবাস", "বাংলা", "গণিত", "সাধারণ জ্ঞান"],
      enrolled: false,
      color: "amber",
    },
  ],
  attempts: [
    {
      id: "seed-1",
      examId: "free-1",
      title: "ফ্রি মডেল টেস্ট ০১",
      answers: { q1: 0, q2: 0, q3: 2, q4: 1, q5: 0 },
      questionIds: ["q1", "q2", "q3", "q4", "q5"],
      score: 3,
      total: 5,
      date: "নমুনা ফলাফল",
    },
  ],
  notifications: [
    {
      title: "আপনার প্রস্তুতি শুরু হোক",
      body: "ফ্রি মডেল টেস্ট দিয়ে নিজের প্রস্তুতি যাচাই করুন।",
    },
    {
      title: "নতুন ইংরেজি কোর্স",
      body: "কোর্স বিভাগ থেকে নমুনা লেসন খুলে পড়তে পারবেন।",
    },
  ],
};
